# Generated by Django 5.1.5 on 2025-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume.', null=True, upload_to='resumes/'),
        ),
    ]
