# Generated by Django 5.1.5 on 2025-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_herosection_resume_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="image",
        ),
        migrations.AddField(
            model_name="skill",
            name="icon_url",
            field=models.URLField(
                default=1, help_text="URL of the skill icon (e.g., Icons8 link)"
            ),
            preserve_default=False,
        ),
    ]
