# Generated by Django 5.1.5 on 2025-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_skill_image_skill_icon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="project",
            name="icon",
        ),
        migrations.AddField(
            model_name="project",
            name="banner_drive_id",
            field=models.CharField(
                default="16ltlizq5IHT6NxcE2E5AzNNAglCTAXu",
                help_text="Google Drive File ID for the project banner",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="icon_drive_id",
            field=models.CharField(
                default="1GURlvkhejDPKKVsKOBNjto8hpgEXIOtZ",
                help_text="Google Drive File ID for the project icon",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(help_text="Project URL"),
        ),
    ]
