# Generated by Django 5.1.5 on 2025-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_project_banner_drive_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="banner_drive_id",
            field=models.CharField(
                help_text="Google Drive File ID for the project banner", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="icon_drive_id",
            field=models.CharField(
                help_text="Google Drive File ID for the project icon", max_length=100
            ),
        ),
    ]
