# Generated by Django 5.1.5 on 2025-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_project_banner_drive_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
        migrations.AddField(
            model_name="course",
            name="image_drive_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive File ID for the course image",
                max_length=100,
                null=True,
            ),
        ),
    ]
