# Generated by Django 5.1.5 on 2025-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_course_image_course_image_drive_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="image",
        ),
        migrations.AddField(
            model_name="certificate",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Technical", "Technical"),
                    ("Non-Technical", "Non-Technical"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="college",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hackathon", "Hackathon"),
                    ("Workshop", "Workshop"),
                    ("Symposium", "Symposium"),
                    ("Competition", "Competition"),
                    ("Certification", "Certification"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="image_drive_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive File ID for certificate image",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issued_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("College", "College"),
                    ("National", "National"),
                    ("International", "International"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="organizer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="won_prize",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
