# Generated by Django 5.1.5 on 2025-04-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_college_organizer_alter_certificate_college_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="url",
        ),
    ]
