# Generated by Django 5.1.5 on 2025-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_eventlist_alter_certificate_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Hackathon', 'Hackathon'), ('Workshop', 'Workshop'), ('Symposium', 'Symposium'), ('Competition', 'Competition'), ('Certification', 'Certification'), ('Bootcamp', 'Bootcamp'), ('Course', 'Course')], max_length=50, null=True),
        ),
    ]
