# Generated by Django 5.1.5 on 2025-04-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_certificate_event_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventList',
        ),
    ]
