# Generated by Django 5.1.5 on 2025-04-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_eventlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='event_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.eventlist'),
            preserve_default=False,
        ),
    ]
