# Generated by Django 5.1.5 on 2025-04-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_eventlist_alter_certificate_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.eventlist'),
        ),
    ]
